<a href="https://colab.research.google.com/github/Sophie-Sherwin/Linear_Algebra_Coding_Projects/blob/main/Gram_Schmidt_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [7]:
#create a vector
r1 = np.array([3, 0, 3, 0])
r1

array([3, 0, 3, 0])

In [8]:
#vector dot product
r1.dot(r1)

18

In [10]:
#magnitude of a vector
np.sqrt(r1.dot(r1))

4.242640687119285

#Gram-Schmidt Orthonormal Process
We'll use the Gram-Schmidt Orthonormal process to find orthogonal vectors in $R^4$

##Our "Random" Vectors:

In [30]:
#create a vector
r1 = np.array([3, 0, 3, 0])

r2 = np.array([3, 2, 3, 3])

r3 = np.array([-7, -4, -5, -6])

r4 = np.array([-7, -3, -11, 2])

## Process $r1$

In [31]:
# Choose the vector and subtract off the orthogonal pieces:
t1 = r1
t1

# Find the size of t1:
m = np.sqrt(t1.dot(t1))

# Create the orthonormal vector u1:
u1 = (1/m) * t1
u1

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [41]:
# Let's check magnitude and orthogonal: 
u1.dot(u1)

1.0000000000000002

## Process $r2$

In [32]:
# Choose the vector and subtract off the orthogonal pieces:
t2 = r2 - (u1.dot(r2))*u1
t2

# Find the size of t2:
m = np.sqrt(t2.dot(t2))

# Create the orthonormal vector u2:
u2 = (1/m) * t2
u2

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [33]:
#essentially: [0, .55, 0, .83]
#Should be: [0, 2/sqrt(13), 0, 3/sqrt(13)]
#Check:
print(2/np.sqrt(13))
print(3/np.sqrt(13))

0.5547001962252291
0.8320502943378437


## Process $r3$

In [34]:
# Choose the vector and subtract off the orthogonal pieces:
t3 = r3 - (u2.dot(r3))*u2 - (u1.dot(r3))*u1
t3

# Find the size of t3:
m = np.sqrt(t3.dot(t3))

# Create the orthonormal vector u3:
u3 = (1/m) * t3
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

In [40]:
#essentially: [-.7, 0, -7, 0]
#Should be: [-1/sqrt(2), 0, 1/sqrt(2), 0]
#Check:
print(-1/np.sqrt(2))
print(1/np.sqrt(2))

-0.7071067811865475
0.7071067811865475


## Process $r4$

In [38]:
# Choose the vector and subtract off the orthogonal pieces:
t4 = r4 - (u3.dot(r4))*u3 - (u2.dot(r4))*u2 - (u1.dot(r4))*u1


# Find the size of t4:
m = np.sqrt(t4.dot(t4))

# Create the orthonormal vector u4:
u4 = (1/m) * t4
u4

array([ 0.        , -0.83205029,  0.        ,  0.5547002 ])

In [39]:
#essentially: [0, -.8, 0, .5]
#Should be: [0, -3/sqrt(13), 0, 2/sqrt(13)]
#Check:
print(2/np.sqrt(13))
print(-3/np.sqrt(13))

0.5547001962252291
-0.8320502943378437


In [ ]:
Print("r1 = ")
Print